"""add telegram_id in inviter

Revision ID: 6885788b20eb
Revises: f1e761d747da
Create Date: 2025-07-11 12:34:36.064971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6885788b20eb'
down_revision: Union[str, Sequence[str], None] = 'f1e761d747da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inviters', sa.Column('telegram_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inviters', 'telegram_id')
    # ### end Alembic commands ###
