"""add click counter

Revision ID: 8a711e5c3ee0
Revises: ea141627c277
Create Date: 2025-07-01 21:19:59.539300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a711e5c3ee0'
down_revision: Union[str, Sequence[str], None] = 'ea141627c277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inviter', sa.Column('click_count', sa.Integer(), nullable=False))
    op.drop_column('inviter', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inviter', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('inviter', 'click_count')
    # ### end Alembic commands ###
