"""create visitors model

Revision ID: a3df03715301
Revises: 8a711e5c3ee0
Create Date: 2025-07-03 22:43:16.919148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3df03715301'
down_revision: Union[str, Sequence[str], None] = '8a711e5c3ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inviters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_code', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_time', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('inviter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inviter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ref_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expire_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('click_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inviter_pkey'))
    )
    op.drop_table('inviters')
    # ### end Alembic commands ###
