"""changing unique ref code

Revision ID: c3b5347cc0e9
Revises: 6885788b20eb
Create Date: 2025-07-11 22:41:34.045987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b5347cc0e9'
down_revision: Union[str, Sequence[str], None] = '6885788b20eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inviters', ['ref_code'])
    op.drop_constraint(op.f('visitors_ref_code_key'), 'visitors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('visitors_ref_code_key'), 'visitors', ['ref_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'inviters', type_='unique')
    # ### end Alembic commands ###
