"""Initial revision

Revision ID: ea141627c277
Revises: f5a0297a0503
Create Date: 2025-07-01 21:02:04.680907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea141627c277'
down_revision: Union[str, Sequence[str], None] = 'f5a0297a0503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inviter', sa.Column('test', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inviter', 'test')
    # ### end Alembic commands ###
