"""Initial revision

Revision ID: f5a0297a0503
Revises: 
Create Date: 2025-07-01 20:54:51.353235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5a0297a0503'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inviter', sa.Column('ref_code', sa.String(), nullable=False))
    op.add_column('inviter', sa.Column('username', sa.String(), nullable=False))
    op.add_column('inviter', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('inviter', sa.Column('expire_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inviter', 'expire_time')
    op.drop_column('inviter', 'created_at')
    op.drop_column('inviter', 'username')
    op.drop_column('inviter', 'ref_code')
    # ### end Alembic commands ###
